#!/usr/bin/zsh -e
# docksh: use a (fresh) Docker container as your shell
# copyright (c) 2015 cyphar <cyphar@cyphar.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# 1. The above copyright notice and this permission notice shall be included in
#    all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

_USER="${DOCKSH_USER:-$USER}"
_SHELL="${DOCKSH_SHELL:-/bin/bash}"
_IMAGE="${DOCKSH_IMAGE:-$HOME/.docksh}"

__signals=("INT" "QUIT" "ABRT" "KILL" "ALRM" "TERM")
__image="$(cat "$_IMAGE")"

function _trap() {
	handle="$1"; shift

	for sig in "$@"; do
		trap "$handle $sig" "$sig"
	done
}

function setup() {
	_trap _pass_signal $__signals
}

function cleanup() {
	nohup docker rm -f "$__container_id" &>/dev/null
	trap "-" $__signals
}

__container_id=""
function _pass_signal() {
	[[ -n "$__container_id" ]] || return;
	echo -e "signal: $1" 1>&2
	return docker kill --signal="$1" "$__container_id" &>/dev/null
}

function _shell() {
	__container_id=$(docker run -d "$__image")
	docker exec -it "$__container_id" sudo -i -u "$_USER" "$_SHELL"
}

setup
_shell
cleanup
